apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: poc-microservices-system
spec:
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
  selector:
    app: customer
  type: NodePort
