apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: poc-microservices-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: akashdocker29/customer:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9002
