apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: poc-microservices-system
spec:
  ports:
  - port: 9004
    targetPort: 9004
    protocol: TCP
  selector:
    app: integration
  type: NodePort
