apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: poc-microservices-system
spec:
  ports:
  - port: 9003
    targetPort: 9003
    protocol: TCP
  selector:
    app: market
  type: NodePort
