apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: market-deployment
  namespace: poc-microservices-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: market
    spec:
      containers:
      - name: market
        image: akashdocker29/market:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9003
